name: Deploy Next.js Static to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: |
          DEPLOY_TARGET=gh-pages npm run build
          cp out/index.html out/404.html
        env:
          NEXT_PUBLIC_BASE_PATH: /wedding-invitation
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          external_repository: adhikagunadarma/wedding-template # repo name not 
          publish_branch: gh-pages
          publish_dir: ./out
